ical:
  poll-period: 300       # How frequently to poll iCal Calendars
  cache-duration: 86400  # How long to cache events when iCal poll fails
  fetch-window: 86400    # How far in advance to fetch events

mqtt:
  host: 10.0.0.5
  port: 1883
  client-id: mqtt-ical
  topic-prefix: "dev/mqtt-ical"

http:
  port: 8080

channel:
  - type: event
    ical:
      match: "Test"
      url: "https://calendar.google.com/calendar/ical/fbu3tbt6va7n7007pgfqr3h068%40group.calendar.google.com/private-b45a5faa71f2e3eb86fb74861f00285d/basic.ics"
    mqtt:
      state:
        topic: test/set
        default: "OFF"
        active: "ON"
        retain: True
        qos: 1
      mode:
        topic: mode

  - type: event
    ical:
      match: "Irrigation Front"
      url: "https://calendar.google.com/calendar/ical/fbu3tbt6va7n7007pgfqr3h068%40group.calendar.google.com/private-b45a5faa71f2e3eb86fb74861f00285d/basic.ics"
    mqtt:
      state:
        topic: front/set
        default: "OFF"
        active: "ON"
        retain: True
        qos: 1
      mode:
        topic: mode

  - type: event
    ical:
      match: "Irrigation Back"
      url: "https://calendar.google.com/calendar/ical/fbu3tbt6va7n7007pgfqr3h068%40group.calendar.google.com/private-b45a5faa71f2e3eb86fb74861f00285d/basic.ics"
    mqtt:
      state:
        topic: back/set
        default: "OFF"
        active: "ON"
        retain: True
        qos: 1
      mode:
        topic: mode
        enable: AUTO
        disable: MANUAL

  - type: event
    ical:
      match: "Irrigation Beds"
      url: "https://calendar.google.com/calendar/ical/fbu3tbt6va7n7007pgfqr3h068%40group.calendar.google.com/private-b45a5faa71f2e3eb86fb74861f00285d/basic.ics"
    mqtt:
      state:
        topic: beds/set
        default: "OFF"
        active: "ON"
        retain: True
        qos: 1
      mode:
        topic: mode
